name: Async standup
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/async-standup.yml

jobs:
  create-standup:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // get the current date in ISO format
            const date = new Date().toISOString().split('T')[0];
            // create new issue in repo
            const issue = await github.rest.issues.create({
              repo: context.repo.repo,
              owner: context.repo.owner,
              title: `Standup for ${date}`,
              body: `Please fill out the following table for ${date}:
              |Who|Name|Priorities 🧐|Progress 😄|Problems 😒|
              |---|---|---|---|---|
              |![rajbos]      |Rob Bos        | | | |
              |![vriesmarcel] |Marcel de Vries| | | |
              |![wulfland]    |Michael Kaufman| | | |
              | | | | | |

              [rajbos]: https://avatars.githubusercontent.com/rajbos?s=80
              [vriesmarcel]: https://avatars.githubusercontent.com/vriesmarcel?s=80
              [wulfland]: https://avatars.githubusercontent.com/wulfland?s=80
              `,
              labels: ['standup'],
            });

            // create comment on this issue to trigger another workflow
            await github.rest.issues.createComment({
              repo: context.repo.repo,
              owner: context.repo.owner,
              issue_number: issue.data.number,
              body: '/giphy scrum standup',
            });