name: Testing my first action
on:
  workflow_dispatch:
  
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: rob-demo/demo-typescript-action@main
        with:
          milliseconds: 100
