name: Environment Demo

on:
  workflow_dispatch:
  
jobs:
  deploy-to-devtest:
    runs-on: ubuntu-latest
    environment: DevTest
    
    steps: 
      - run: echo "Hello world"

  deploy-to-prod:
    runs-on: ubuntu-latest
    environment: PRD
    
    steps: 
      - run: echo "Hello world"
