name: Order a pizza

on:
  workflow_dispatch:

jobs:
  pizza:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: pizza
      uses: rajbos-actions/dominos-action@demotime
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        address: ${{ secrets.ADDRESS }}
        order-type: ${{ secrets.ORDER_TYPE }}
        email: ${{ secrets.EMAIL }}
        phone: ${{ secrets.PHONE }}
        first-name: ${{ secrets.FIRST_NAME }}
        last-name: ${{ secrets.LAST_NAME }}
        card-number: ${{ secrets.CARD_NUMBER }}
        expiration: ${{ secrets.EXPIRATION }}
        security-code: ${{ secrets.SECURITY_CODE }}
        card-postal-code: ${{ secrets.CARD_POSTAL_CODE }}
        active: false



















































    - run: echo "![turles say pizza time](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExNjE0OGM2MjM3OTljYzM5MWM1MGJlNTgyMjI0NTNhNDA5MTRiMTZlYyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/kN8P8JcB64fja/giphy.gif)" >> $GITHUB_STEP_SUMMARY